package com.mmg.manahub.core.model

/**
 * How a deck came into existence, carried by the one-time `DeckCreated` progression event.
 *
 * Only user-authored decks ([isUserAuthored]) earn deck XP and advance the "build a deck" quest;
 * every source still counts toward the DERIVED deck achievements, because the deck is real.
 */
enum class DeckCreationSource {
    /** Built by hand in Deck Studio or the deck list. */
    BUILT,

    /** Generated by the Deck Wizard. */
    WIZARD,

    /** Created from a pasted or uploaded deck list. */
    IMPORT,

    /** Imported from a community deck (Archidekt). */
    COMMUNITY,

    /** Saved from the Draft Simulator. */
    DRAFT;

    /** True for decks the user built themselves (XP + quest eligible). */
    val isUserAuthored: Boolean get() = this == BUILT || this == WIZARD
}
