import java.util.Properties

plugins {
    alias(libs.plugins.android.application)
    // KMP migration — Phase 3: required for merging Compose Multiplatform resources
    // from :shared:core-ui into the Android assets.
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.ksp)
    alias(libs.plugins.hilt)
    alias(libs.plugins.google.services)
    alias(libs.plugins.firebase.crashlytics)
}

compose.resources {
    packageOfResClass = "com.mmg.manahub"
}

// KMP migration — Phase 3: Manually bridge CMP resources from :shared:core-ui
// until the experimental android-kmp-library + CMP resource merging is stabilized.
// This task corrects the "flat" asset structure generated by CMP into the namespaced
// structure expected by the generated Res code.
val prepareCmpAssets by tasks.registering(Copy::class) {
    // KMP migration — Phase 3: Explicitly depend on the resource generation task in :shared:core-ui
    // to fix the "uses output without declaring dependency" build error.
    dependsOn(":shared:core-ui:prepareComposeResourcesTaskForCommonMain")
    from(project(":shared:core-ui").layout.buildDirectory.dir("generated/compose/resourceGenerator/preparedResources/commonMain"))
    into(layout.buildDirectory.dir("generated/cmp-assets"))
    eachFile {
        if (path.startsWith("composeResources/") && !path.contains("com.mmg.manahub.core.ui")) {
            path = path.replaceFirst("composeResources/", "composeResources/com.mmg.manahub.core.ui/")
        }
    }
    includeEmptyDirs = false
}

val localProperties = Properties()
val localPropertiesFile = rootProject.file("local.properties")
if (localPropertiesFile.exists()) {
    localPropertiesFile.inputStream().use { localProperties.load(it) }
}

fun requiredProperty(name: String): String =
    localProperties.getProperty(name)
        ?: System.getenv(name)
        ?: error("Missing required build property: $name. Add it to local.properties or set as environment variable in CI.")

android {
    namespace = "com.mmg.manahub"
    compileSdk = 37

    defaultConfig {
        applicationId = "com.mmg.manahub"
        minSdk = 29
        targetSdk = 36
        versionCode = 1
        versionName = "0"

        buildConfigField(
            "String",
            "YOUTUBE_API_KEY",
            "\"${localProperties.getProperty("YOUTUBE_API_KEY", "")}\""
        )
        buildConfigField(
            "String",
            "SUPABASE_URL",
            "\"${requiredProperty("SUPABASE_URL")}\""
        )
        buildConfigField(
            "String",
            "SUPABASE_ANON_KEY",
            "\"${requiredProperty("SUPABASE_ANON_KEY")}\""
        )
        buildConfigField(
            "String",
            "GOOGLE_CLIENT_ID",
            "\"${requiredProperty("GOOGLE_CLIENT_ID")}\""
        )
        buildConfigField(
            "String",
            "CLOUDFLARE_WORKER_URL",
            "\"${localProperties.getProperty("CLOUDFLARE_WORKER_URL", "https://manahub-draft-api.miguel-mglez.workers.dev/")}\""
        )
        buildConfigField(
            "String",
            "COMMUNITY_WORKER_URL",
            // The `manahub-community` Worker (Deck Doctor Community/Archetype plan, Phase 3.3) is
            // deployed at this real workers.dev subdomain as of 2026-07-12. Trailing slash is
            // required — CommunityAggregateApi builds request URLs via "${baseUrl}v1/..." string
            // concatenation (see its KDoc: "must end with `/`"), matching the CLOUDFLARE_WORKER_URL
            // convention above.
            "\"${localProperties.getProperty("COMMUNITY_WORKER_URL", "https://manahub-community.miguel-mglez.workers.dev/")}\""
        )

        ndk {
            abiFilters += listOf("arm64-v8a", "x86_64")
        }
    }

    testOptions {
        unitTests {
            isReturnDefaultValues = true
            all {
                // The suite has grown large enough (~2000 tests across many heavily-mocked
                // ViewModels/repositories) that the JVM's default test-worker heap intermittently
                // exhausts mid-run and cascades into unrelated OutOfMemoryErrors (confirmed
                // reproducible: two separate full runs failed on the exact same unrelated test
                // classes — LobbyJoinViewModelTest, SavePlaytestUseCaseTest,
                // OnlineSessionRepositoryImplTest, CollectionSyncTest, SyncManagerTest — never on
                // anything touched by the change that happened to be in flight). Bump the worker
                // heap so `./gradlew test`/`testDebugUnitTest` can complete deterministically.
                it.maxHeapSize = "4096m"

                // Wizard Quality Campaign harness (Wave 1 KNOWN LIMITATION, fixed Wave 2): Gradle's
                // `Test` task does NOT forward arbitrary `-D` JVM system properties from the CLI to
                // the forked test worker on its own -- `-Dharness.runLabel=wave2` on the command
                // line was silently lost, so every harness report's `label` field read "baseline"
                // regardless of what was passed. Forward it explicitly via a Gradle PROJECT property
                // (`-Pharness.runLabel=wave2`, not `-D`) so WizardQualityMatrixTest's
                // `System.getProperty("harness.runLabel", "baseline")` actually sees it.
                it.systemProperty(
                    "harness.runLabel",
                    (project.findProperty("harness.runLabel") as String?) ?: "baseline",
                )
            }
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlin {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
        }
    }

    signingConfigs {
        create("release") {
            val keystorePath = localProperties.getProperty("KEY_STORE_PATH", "")
            if (keystorePath.isNotEmpty()) {
                storeFile = file(keystorePath)
            }
            storePassword = localProperties.getProperty("KEY_STORE_PASSWORD", "")
            keyAlias = localProperties.getProperty("KEY_ALIAS", "")
            keyPassword = localProperties.getProperty("KEY_PASSWORD", "")
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
            signingConfig = signingConfigs.getByName("release")
        }
        debug {
            isMinifyEnabled = false
        }
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    packaging {
        jniLibs {
            useLegacyPackaging = false
        }
    }

    androidResources {
        noCompress += listOf("tflite", "cvr")
    }

    ksp {
        arg("room.schemaLocation", "$projectDir/schemas")
        arg("hilt.incremental", "false")
    }

    // Expose the exported Room schemas to instrumented tests so MigrationTestHelper
    // can load them from androidTest assets (required by Room 2.8 MigrationTestHelper).
    sourceSets {
        getByName("main") {
            // KMP migration — Phase 3: Manually link CMP resources from :shared:core-ui
            // until the android-kmp-library + CMP resource merging is stabilized.
            assets.srcDirs(
                file("build/generated/cmp-assets")
            )
        }
        getByName("androidTest") {
            assets.srcDirs("$projectDir/schemas")
        }
    }

    // Ensure assets are prepared before merging or linting (Phase 3 CMP resource bridging).
    // lintVitalAnalyzeRelease scans assets and needs an explicit dependency on the generator.
    tasks.configureEach {
        val taskName = name
        if ((taskName.startsWith("merge") && taskName.endsWith("Assets")) ||
            taskName.contains("lintVitalAnalyze", ignoreCase = true) ||
            taskName.contains("lintAnalyze", ignoreCase = true) ||
            (taskName.startsWith("generate") && taskName.contains("Lint") && taskName.contains("Model"))
        ) {
            dependsOn(prepareCmpAssets)
        }
    }
}



dependencies {
    // KMP migration — Phase 0, Spike A: shared pure-Kotlin domain models (CollectionViewMode, GroupingMode).
    implementation(project(":shared:core-model"))
    // KMP migration — Phase 1: shared cross-cutting contracts (DispatcherProvider, KeyValueStore,
    // CrashReporter, Page). Depended on so it builds with :app; call-sites are NOT migrated onto it yet.
    implementation(project(":shared:core-common"))
    // KMP migration — Phase 2 / Slice 1: shared domain contracts (a first batch of pure repository
    // interfaces — UserPreferences/Stats/CommunityStats/NotificationPrefs/PushToken — live here now).
    implementation(project(":shared:core-domain"))
    // KMP migration — Phase 2: shared data layer (rate-limit queues, later repo impls + Ktor).
    implementation(project(":shared:core-data"))
    // KMP migration — Phase 3 / Slice 1: shared design system (MagicTheme tokens, colors,
    // spacing, shapes, Material 3 bridge). Typography/font-loading remain in :app.
    implementation(project(":shared:core-ui"))
    implementation(compose.components.resources)

    // Supabase Auth & DB
    val supabaseBom = platform(libs.supabase.bom)
    implementation(supabaseBom)
    implementation(libs.supabase.auth)
    implementation(libs.supabase.postgrest)
    implementation(libs.supabase.realtime)
    implementation(libs.ktor.android)
    implementation(libs.ktor.client.okhttp)
    implementation(libs.ktor.client.content.negotiation)
    implementation(libs.ktor.serialization.kotlinx.json)

    // Google Sign-In
    implementation(libs.credentials)
    implementation(libs.credentials.play)
    implementation(libs.googleid)

    // Firebase
    implementation(libs.firebase.crashlytics)
    implementation(libs.splashscreen)
    implementation(libs.foundation)
    implementation(libs.material3)
    // tv.material removed — no usages found in the codebase (verified 2026-06-10)
    implementation(libs.emojis)
    val composeBom = platform(libs.compose.bom)
    implementation(composeBom)
    implementation(libs.compose.ui)
    implementation(libs.compose.material3)
    implementation(libs.compose.tooling.preview)
    debugImplementation(libs.compose.tooling)

    implementation(libs.navigation.compose)
    implementation(libs.lifecycle.viewmodel)
    implementation(libs.lifecycle.runtime)

    implementation(libs.hilt.android)
    ksp(libs.hilt.compiler)
    implementation(libs.hilt.navigation)

    // Koin — Phase 0 Spike D: runs ALONGSIDE Hilt to enable a per-feature Hilt→Koin cutover
    // (the Settings feature is the first "Koin island"; the rest stays on Hilt). Additive — no
    // Hilt dependency removed. koin-androidx-compose supplies koinViewModel() for Composables.
    implementation(libs.koin.core)
    implementation(libs.koin.android)
    implementation(libs.koin.androidx.compose)
    // KMP migration — Hilt→Koin cutover batch 6: WorkManager subsystem. `worker { }` DSL +
    // KoinWorkerFactory for the 7 non-excluded @HiltWorkers (see core.di.SyncModule).
    implementation(libs.koin.androidx.workmanager)

    implementation(libs.room.runtime)
    implementation(libs.room.ktx)
    ksp(libs.room.compiler)

    implementation(libs.retrofit)
    implementation(libs.retrofit.gson)  // Kept for DraftModule (Cloudflare/YouTube manual JSON parsing)
    implementation(libs.okhttp.logging)
    implementation(libs.kotlinx.serialization.json)
    implementation(libs.kotlinx.datetime)
    implementation(libs.retrofit.kotlinx.serialization.converter)

    implementation(libs.coil.compose)
    implementation(libs.coil.svg)
    implementation(libs.coil.network.okhttp)

    implementation(libs.camerax.camera2)
    implementation(libs.camerax.lifecycle)
    implementation(libs.camerax.view)

    testImplementation(libs.junit)
    testImplementation(libs.mockk)
    testImplementation(libs.turbine)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.arch.core.testing)
    testImplementation(libs.okhttp.mockwebserver)

    androidTestImplementation(libs.androidx.test.ext.junit)
    androidTestImplementation(libs.espresso.core)
    androidTestImplementation(libs.room.testing)
    androidTestImplementation(libs.coroutines.test)
    androidTestImplementation(libs.turbine)

    // Gson — needed directly by RoomConverters and CardEntityMapper
    implementation(libs.gson)

    // implementation("org.tensorflow:tensorflow-lite:2.16.1")
    // implementation("org.tensorflow:tensorflow-lite-support:0.4.4")

    // Latin-only: ja/ko variants removed 2026-07-22 (Android 16 / API 36 migration) — their
    // native libraries are not 16KB-page-size aligned and no fixed release exists upstream.
    implementation("com.google.android.gms:play-services-mlkit-text-recognition:19.0.1")

    implementation(libs.accompanist.permissions)
    implementation(libs.material.icons.extended)
    implementation(libs.compose.googlefonts)
    implementation(libs.datastore.preferences)
    implementation(libs.paging.runtime)
    implementation(libs.paging.compose)
    implementation(libs.room.paging)
    implementation(libs.work.runtime)
    implementation(libs.hilt.work)
    ksp(libs.hilt.work.compiler)
    implementation(libs.browser)
    implementation(libs.guava)

    implementation(platform(libs.firebase.bom))
    implementation(libs.firebase.analytics)
    implementation(libs.firebase.messaging)
    implementation(libs.youtube.player)

    // Nearby Connections — peer-to-peer in-person game state sync
    implementation("com.google.android.gms:play-services-nearby:19.3.0")

    implementation(libs.play.app.update)
    implementation(libs.play.review)

    // Vosk — offline grammar-restricted voice recognition
    implementation(libs.vosk.android)

    // Stable collection types for Compose recomposition stability
    implementation(libs.kotlinx.collections.immutable)
}

hilt {
    enableAggregatingTask = false
}
