package com.mmg.manahub.core.data.local.dao

import android.content.Context
import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import com.mmg.manahub.core.data.local.MtgDatabase
import com.mmg.manahub.core.data.local.entity.XpTransactionEntity
import com.mmg.manahub.core.gamification.domain.LevelCurve
import com.mmg.manahub.core.gamification.domain.model.XpSourceCategory
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.async
import kotlinx.coroutines.awaitAll
import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.runBlocking
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

/**
 * Instrumented Room tests for [GamificationDao.grantXpAtomically] — the C1 lost-update regression.
 *
 * Requires a connected device or emulator.
 *
 * Uses an in-memory [MtgDatabase] so tests are hermetic and do not touch the real on-device database
 * file. The DB is created fresh for every test method via [createDatabase]/[closeDatabase].
 *
 * The concurrency test deliberately runs REAL concurrent transactions on `Dispatchers.IO` (via
 * `runBlocking`, NOT `runTest`) so Room's transaction locking is genuinely exercised. The whole point
 * is that the new delta-based grant reads the current total INSIDE the transaction, so 200 racing
 * grants with distinct idempotency keys must sum exactly with no lost updates.
 *
 * NOTE: These tests were written correctly but were NOT executed against a device or emulator because
 * no connected device was available at the time of writing. Run them with
 * `./gradlew connectedAndroidTest` after connecting a device.
 */
@RunWith(AndroidJUnit4::class)
class GamificationDaoConcurrencyTest {

    // ── In-memory database ────────────────────────────────────────────────────

    private lateinit var db: MtgDatabase
    private lateinit var dao: GamificationDao

    @Before
    fun createDatabase() {
        val context = ApplicationProvider.getApplicationContext<Context>()
        // NOTE: deliberately NOT allowMainThreadQueries() — the concurrency test needs real IO-thread
        // transactions so Room's locking is exercised rather than serialized onto the main thread.
        db = Room.inMemoryDatabaseBuilder(context, MtgDatabase::class.java).build()
        dao = db.gamificationDao()
    }

    @After
    fun closeDatabase() {
        db.close()
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    /**
     * Builds a ledger row for [key]/[amount]. [id] defaults to 0 (auto-generated by Room on insert).
     */
    private fun makeTxn(
        key: String,
        amount: Int,
        sourceRef: String? = key,
        createdAt: Long = 0L,
    ): XpTransactionEntity = XpTransactionEntity(
        idempotencyKey = key,
        amount = amount,
        sourceCategory = XpSourceCategory.GAME.name,
        sourceRef = sourceRef,
        createdAt = createdAt,
    )

    // ── C1: no lost update under concurrency ──────────────────────────────────

    @Test
    fun `many concurrent grants with distinct keys never lose an update`() = runBlocking {
        val grants = 200
        val amountEach = 7

        // Fire all grants concurrently on the IO dispatcher; each has a DISTINCT idempotency key, so
        // none is a duplicate — every one must be applied and contribute to the running total.
        val results = coroutineScope {
            (1..grants).map { i ->
                async(Dispatchers.IO) {
                    dao.grantXpAtomically(
                        txn = makeTxn(key = "key-$i", amount = amountEach),
                        amount = amountEach,
                        updatedAt = i.toLong(),
                        levelForTotalXp = LevelCurve::levelForTotalXp,
                    )
                }
            }.awaitAll()
        }

        // Every grant must have applied (distinct keys → no duplicates).
        assertEquals("all distinct-key grants must apply", grants, results.count { it.applied })

        val ledgerSum = dao.sumAllXp()
        val progression = dao.getProgression()!!

        assertEquals("ledger must total N * amount", grants.toLong() * amountEach, ledgerSum)
        // The crux: progression.total_xp must equal the ledger sum — no concurrent grant clobbered another.
        assertEquals("progression total must equal ledger sum (no lost update)", ledgerSum, progression.totalXp)
        assertEquals(
            "progression level must match the curve for the final total",
            LevelCurve.levelForTotalXp(ledgerSum),
            progression.level,
        )
    }

    // ── Duplicate key is a no-op ──────────────────────────────────────────────

    @Test
    fun `a duplicate idempotency key is a no-op and does not double-grant`() = runBlocking {
        val first = dao.grantXpAtomically(
            txn = makeTxn(key = "dup", amount = 10),
            amount = 10,
            updatedAt = 1L,
            levelForTotalXp = LevelCurve::levelForTotalXp,
        )
        assertTrue("first grant must apply", first.applied)
        assertEquals(10L, first.newTotalXp)

        val second = dao.grantXpAtomically(
            txn = makeTxn(key = "dup", amount = 10),
            amount = 10,
            updatedAt = 2L,
            levelForTotalXp = LevelCurve::levelForTotalXp,
        )

        assertFalse("a duplicate key must NOT apply", second.applied)
        // The unchanged state is reported on the no-op.
        assertEquals("previous == new on a no-op", second.previousTotalXp, second.newTotalXp)
        assertEquals("no-op reports the unchanged total (10)", 10L, second.newTotalXp)

        // Nothing was double-counted: both ledger sum and progression stay at 10.
        assertEquals("ledger must still total 10", 10L, dao.sumAllXp())
        assertEquals("progression total must still be 10", 10L, dao.getProgression()!!.totalXp)
    }
}
