package com.mmg.manahub.core.data.local.dao

import android.content.Context
import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import app.cash.turbine.test
import com.mmg.manahub.core.data.local.MtgDatabase
import com.mmg.manahub.core.data.local.entity.PlaytestCardStatEntity
import com.mmg.manahub.core.data.local.entity.PlaytestSessionEntity
import com.mmg.manahub.core.data.local.entity.PlaytestSurveyAnswerEntity
import kotlinx.coroutines.test.runTest
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

/**
 * Instrumented Room tests for [PlaytestDao].
 *
 * Requires a connected device or emulator.
 *
 * Uses an in-memory [MtgDatabase] so tests are hermetic and do not touch the
 * real on-device database file. The in-memory DB is created fresh for every
 * test method via [setUp]/[tearDown].
 *
 * NOTE: These tests were written correctly but were NOT executed against a device
 * or emulator because no connected device was available at the time of writing.
 * Run them with `./gradlew connectedAndroidTest` after connecting a device.
 */
@RunWith(AndroidJUnit4::class)
class PlaytestDaoInstrumentedTest {

    // ── In-memory database ────────────────────────────────────────────────────

    private lateinit var db: MtgDatabase
    private lateinit var dao: PlaytestDao

    @Before
    fun createDatabase() {
        val context = ApplicationProvider.getApplicationContext<Context>()
        db = Room.inMemoryDatabaseBuilder(context, MtgDatabase::class.java)
            .allowMainThreadQueries()  // Safe for in-memory tests; avoids executor complexity.
            .build()
        dao = db.playtestDao()
    }

    @After
    fun closeDatabase() {
        db.close()
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    /**
     * Minimal [PlaytestSessionEntity] with all required fields.
     * [id] defaults to 0 (auto-generated by Room on insert).
     */
    private fun makeSession(
        deckId: String = "deck-1",
        format: String = "standard",
        drawCount: Int = 7,
        mulligansUsed: Int = 0,
        librarySize: Int = 53,
        onThePlay: Boolean = true,
        startedAt: Long = System.currentTimeMillis(),
    ): PlaytestSessionEntity = PlaytestSessionEntity(
        id            = 0,
        deckId        = deckId,
        format        = format,
        drawCount     = drawCount,
        mulligansUsed = mulligansUsed,
        librarySize   = librarySize,
        onThePlay     = onThePlay,
        startedAt     = startedAt,
    )

    /**
     * Builds a [PlaytestCardStatEntity] for a given session id and scryfall id.
     * [playtestSessionId] is set to 0 here and stamped with the real id by
     * [PlaytestDao.saveTestAtomically], mirroring production usage.
     */
    private fun makeCardStat(
        scryfallId: String,
        copiesInOpeningHand: Int = 1,
        copiesBottomedOnMulligan: Int = 0,
    ): PlaytestCardStatEntity = PlaytestCardStatEntity(
        id                     = 0,
        playtestSessionId      = 0,  // Stamped by saveTestAtomically
        scryfallId             = scryfallId,
        copiesInOpeningHand    = copiesInOpeningHand,
        copiesBottomedOnMulligan = copiesBottomedOnMulligan,
    )

    /**
     * Minimal survey answer for the given session id and question id.
     */
    private fun makeSurveyAnswer(
        playtestSessionId: Long,
        questionId: String = "HAND_FEEL",
        answer: String = "GOOD",
        deckId: String = "deck-1",
    ): PlaytestSurveyAnswerEntity = PlaytestSurveyAnswerEntity(
        id                = 0,
        playtestSessionId = playtestSessionId,
        questionId        = questionId,
        questionType      = "HAND",
        answer            = answer,
        deckId            = deckId,
    )

    // ── Group 1: saveTestAtomically ───────────────────────────────────────────

    @Test
    fun `given session and card stats when saveTestAtomically then new session id is returned`() = runTest {
        val cardStats = listOf(makeCardStat("bolt"), makeCardStat("birds"))

        val sessionId = dao.saveTestAtomically(makeSession(), cardStats)

        assertTrue("auto-generated session id must be > 0", sessionId > 0L)
    }

    @Test
    fun `given session and card stats when saveTestAtomically then getCardStatsForSession returns all rows with correct sessionId`() = runTest {
        val cardStats = listOf(
            makeCardStat("bolt", copiesInOpeningHand = 2),
            makeCardStat("birds", copiesInOpeningHand = 1),
            makeCardStat("land", copiesInOpeningHand = 1),
        )

        val sessionId = dao.saveTestAtomically(makeSession(), cardStats)

        val savedStats = dao.getCardStatsForSession(sessionId)
        assertEquals("all 3 card stat rows must be returned", 3, savedStats.size)
        assertTrue(
            "every stat row must have the new session id stamped",
            savedStats.all { it.playtestSessionId == sessionId },
        )
    }

    @Test
    fun `given session with no card stats when saveTestAtomically then session is saved and getCardStatsForSession returns empty`() = runTest {
        val sessionId = dao.saveTestAtomically(makeSession(), emptyList())

        assertTrue("session id must be > 0 even with no card stats", sessionId > 0L)

        val savedStats = dao.getCardStatsForSession(sessionId)
        assertTrue("card stats must be empty when none were passed", savedStats.isEmpty())
    }

    @Test
    fun `given two sessions saved when getCardStatsForSession called for each then stats are scoped correctly`() = runTest {
        val statsForSession1 = listOf(makeCardStat("bolt"))
        val statsForSession2 = listOf(makeCardStat("birds"), makeCardStat("land"))

        val id1 = dao.saveTestAtomically(makeSession(deckId = "deck-1"), statsForSession1)
        val id2 = dao.saveTestAtomically(makeSession(deckId = "deck-2"), statsForSession2)

        val result1 = dao.getCardStatsForSession(id1)
        val result2 = dao.getCardStatsForSession(id2)

        assertEquals(1, result1.size)
        assertEquals("bolt", result1[0].scryfallId)
        assertEquals(2, result2.size)
    }

    // ── Group 2: CASCADE DELETE ───────────────────────────────────────────────

    @Test
    fun `given session with card stats and survey answers when session is deleted then all child rows are removed`() = runTest {
        val cardStats = listOf(makeCardStat("bolt"), makeCardStat("birds"))
        val sessionId = dao.saveTestAtomically(makeSession(), cardStats)

        // Attach survey answers.
        val answers = listOf(
            makeSurveyAnswer(playtestSessionId = sessionId, questionId = "HAND_FEEL"),
            makeSurveyAnswer(playtestSessionId = sessionId, questionId = "MANA_CURVE"),
        )
        dao.replacePlaytestSurveyAnswers(sessionId, answers)

        // Verify rows exist before delete.
        assertEquals(2, dao.getCardStatsForSession(sessionId).size)
        assertEquals(2, dao.getSurveyAnswersForSession(sessionId).size)

        // Delete the parent session via raw SQL.
        db.openHelper.writableDatabase.execSQL(
            "DELETE FROM playtest_sessions WHERE id = $sessionId"
        )

        // CASCADE should have removed all child rows.
        val statsAfter = dao.getCardStatsForSession(sessionId)
        val surveyAfter = dao.getSurveyAnswersForSession(sessionId)

        assertTrue("card stat rows must be cascade-deleted", statsAfter.isEmpty())
        assertTrue("survey answer rows must be cascade-deleted", surveyAfter.isEmpty())
    }

    @Test
    fun `given two sessions when one session is deleted then only its child rows are removed`() = runTest {
        val statsForSession1 = listOf(makeCardStat("bolt"))
        val statsForSession2 = listOf(makeCardStat("birds"))

        val id1 = dao.saveTestAtomically(makeSession(), statsForSession1)
        val id2 = dao.saveTestAtomically(makeSession(), statsForSession2)

        // Delete only session 1.
        db.openHelper.writableDatabase.execSQL(
            "DELETE FROM playtest_sessions WHERE id = $id1"
        )

        // Session 2's stats must be intact.
        assertTrue("session1 stats must be cascade-deleted", dao.getCardStatsForSession(id1).isEmpty())
        assertEquals("session2 stats must be untouched", 1, dao.getCardStatsForSession(id2).size)
    }

    // ── Group 3: observeTestCountForDeck ─────────────────────────────────────

    @Test
    fun `given no sessions for deck when observeTestCountForDeck called then emits 0`() = runTest {
        dao.observeTestCountForDeck("deck-empty").test {
            assertEquals("initial count must be 0 for a deck with no sessions", 0, awaitItem())
            cancelAndIgnoreRemainingEvents()
        }
    }

    @Test
    fun `given sessions saved one by one when observeTestCountForDeck observed then count increments`() = runTest {
        dao.observeTestCountForDeck("deck-1").test {
            assertEquals(0, awaitItem())

            dao.saveTestAtomically(makeSession(deckId = "deck-1"), emptyList())
            assertEquals(1, awaitItem())

            dao.saveTestAtomically(makeSession(deckId = "deck-1"), emptyList())
            assertEquals(2, awaitItem())

            cancelAndIgnoreRemainingEvents()
        }
    }

    @Test
    fun `given sessions for multiple decks when observeTestCountForDeck called for one deck then only that deck is counted`() = runTest {
        dao.saveTestAtomically(makeSession(deckId = "deck-A"), emptyList())
        dao.saveTestAtomically(makeSession(deckId = "deck-A"), emptyList())
        dao.saveTestAtomically(makeSession(deckId = "deck-B"), emptyList())

        dao.observeTestCountForDeck("deck-A").test {
            assertEquals("count for deck-A must be 2", 2, awaitItem())
            cancelAndIgnoreRemainingEvents()
        }

        dao.observeTestCountForDeck("deck-B").test {
            assertEquals("count for deck-B must be 1", 1, awaitItem())
            cancelAndIgnoreRemainingEvents()
        }
    }

    // ── Group 4: observeCardAppearanceStatsForDeck ────────────────────────────

    @Test
    fun `given multiple saved tests with same scryfallId when observeCardAppearanceStatsForDeck called then copies are summed`() = runTest {
        // Test 1: 2 copies of "bolt" in hand.
        val id1 = dao.saveTestAtomically(
            makeSession(deckId = "deck-1"),
            listOf(makeCardStat("bolt", copiesInOpeningHand = 2)),
        )
        // Test 2: 1 copy of "bolt" in hand.
        val id2 = dao.saveTestAtomically(
            makeSession(deckId = "deck-1"),
            listOf(makeCardStat("bolt", copiesInOpeningHand = 1)),
        )

        dao.observeCardAppearanceStatsForDeck("deck-1").test {
            val rows = awaitItem()
            assertEquals("must return exactly 1 row for bolt", 1, rows.size)

            val boltRow = rows[0]
            assertEquals("bolt", boltRow.scryfallId)
            assertEquals(
                "totalCopiesInHand must sum across both tests: 2+1=3",
                3,
                boltRow.totalCopiesInHand,
            )
            assertEquals(
                "testsWithAppearance must count distinct session ids",
                2,
                boltRow.testsWithAppearance,
            )
            cancelAndIgnoreRemainingEvents()
        }
    }

    @Test
    fun `given no saved tests for deck when observeCardAppearanceStatsForDeck called then emits empty list`() = runTest {
        dao.observeCardAppearanceStatsForDeck("deck-empty").test {
            assertTrue("must emit empty list when no tests saved", awaitItem().isEmpty())
            cancelAndIgnoreRemainingEvents()
        }
    }

    @Test
    fun `given saved tests for multiple decks when observeCardAppearanceStatsForDeck for one deck then only that deck aggregated`() = runTest {
        dao.saveTestAtomically(
            makeSession(deckId = "deck-A"),
            listOf(makeCardStat("bolt", copiesInOpeningHand = 3)),
        )
        dao.saveTestAtomically(
            makeSession(deckId = "deck-B"),
            listOf(makeCardStat("bolt", copiesInOpeningHand = 10)),
        )

        dao.observeCardAppearanceStatsForDeck("deck-A").test {
            val rows = awaitItem()
            assertEquals(1, rows.size)
            assertEquals(
                "totalCopiesInHand must only count deck-A sessions",
                3,
                rows[0].totalCopiesInHand,
            )
            cancelAndIgnoreRemainingEvents()
        }
    }

    // ── Group 5: observeCardAppearanceStatsForDeckAndCard ─────────────────────

    @Test
    fun `given card never appeared when observeCardAppearanceStatsForDeckAndCard called then emits null`() = runTest {
        // Save a session with "birds" but query for "bolt" which was never saved.
        dao.saveTestAtomically(
            makeSession(deckId = "deck-1"),
            listOf(makeCardStat("birds", copiesInOpeningHand = 1)),
        )

        dao.observeCardAppearanceStatsForDeckAndCard("deck-1", "bolt").test {
            assertNull(
                "must emit null when card never appeared in any saved test",
                awaitItem(),
            )
            cancelAndIgnoreRemainingEvents()
        }
    }

    @Test
    fun `given card appeared in multiple tests when observeCardAppearanceStatsForDeckAndCard called then emits aggregate row`() = runTest {
        dao.saveTestAtomically(
            makeSession(deckId = "deck-1"),
            listOf(
                makeCardStat("bolt", copiesInOpeningHand = 2, copiesBottomedOnMulligan = 1),
            ),
        )
        dao.saveTestAtomically(
            makeSession(deckId = "deck-1"),
            listOf(
                makeCardStat("bolt", copiesInOpeningHand = 1, copiesBottomedOnMulligan = 0),
            ),
        )

        dao.observeCardAppearanceStatsForDeckAndCard("deck-1", "bolt").test {
            val row = awaitItem()
            assertNotNull("row must not be null when card appeared", row)
            assertEquals("bolt", row!!.scryfallId)
            assertEquals("totalCopiesInHand = 2+1 = 3", 3, row.totalCopiesInHand)
            assertEquals("totalCopiesBottomed = 1+0 = 1", 1, row.totalCopiesBottomed)
            assertEquals("testsWithAppearance must count 2 distinct sessions", 2, row.testsWithAppearance)
            cancelAndIgnoreRemainingEvents()
        }
    }

    @Test
    fun `given no saved tests for deck when observeCardAppearanceStatsForDeckAndCard called then emits null`() = runTest {
        dao.observeCardAppearanceStatsForDeckAndCard("deck-empty", "bolt").test {
            assertNull("must emit null when deck has no tests", awaitItem())
            cancelAndIgnoreRemainingEvents()
        }
    }

    // ── Group 6: replacePlaytestSurveyAnswers idempotency ─────────────────────

    @Test
    fun `given survey answers saved twice for same session when replacePlaytestSurveyAnswers called then rows are NOT accumulated`() = runTest {
        // Mirrors the SurveyAnswerDao.replaceAnswersForSession pattern.
        val sessionId = dao.saveTestAtomically(makeSession(), emptyList())

        val firstAnswers = listOf(
            makeSurveyAnswer(sessionId, questionId = "HAND_FEEL", answer = "GOOD"),
            makeSurveyAnswer(sessionId, questionId = "MANA_CURVE", answer = "SMOOTH"),
        )
        dao.replacePlaytestSurveyAnswers(sessionId, firstAnswers)

        val firstSave = dao.getSurveyAnswersForSession(sessionId)
        assertEquals("first save must yield 2 rows", 2, firstSave.size)

        // Second call with different answers (user re-submitted the survey).
        val secondAnswers = listOf(
            makeSurveyAnswer(sessionId, questionId = "HAND_FEEL", answer = "BAD"),
            makeSurveyAnswer(sessionId, questionId = "MANA_CURVE", answer = "FLOODED"),
        )
        dao.replacePlaytestSurveyAnswers(sessionId, secondAnswers)

        val secondSave = dao.getSurveyAnswersForSession(sessionId)
        assertEquals("second save must still yield 2 rows, NOT 4", 2, secondSave.size)
        assertEquals("answers must reflect the second submission", "BAD", secondSave.find { it.questionId == "HAND_FEEL" }?.answer)
    }

    @Test
    fun `given survey saved then replaced with empty list when replacePlaytestSurveyAnswers called then all rows removed`() = runTest {
        val sessionId = dao.saveTestAtomically(makeSession(), emptyList())

        val answers = listOf(
            makeSurveyAnswer(sessionId, questionId = "HAND_FEEL", answer = "GOOD"),
        )
        dao.replacePlaytestSurveyAnswers(sessionId, answers)
        assertEquals("first save must yield 1 row", 1, dao.getSurveyAnswersForSession(sessionId).size)

        // Replace with empty list simulates user clearing the survey.
        dao.replacePlaytestSurveyAnswers(sessionId, emptyList())

        assertTrue(
            "all survey rows must be removed after replacing with empty list",
            dao.getSurveyAnswersForSession(sessionId).isEmpty(),
        )
    }

    @Test
    fun `given survey answers for two sessions when replace called for one then only that session is affected`() = runTest {
        val id1 = dao.saveTestAtomically(makeSession(), emptyList())
        val id2 = dao.saveTestAtomically(makeSession(), emptyList())

        dao.replacePlaytestSurveyAnswers(id1, listOf(makeSurveyAnswer(id1, questionId = "Q1", answer = "A1")))
        dao.replacePlaytestSurveyAnswers(id2, listOf(makeSurveyAnswer(id2, questionId = "Q2", answer = "A2")))

        // Replace only session 1's answers.
        dao.replacePlaytestSurveyAnswers(id1, listOf(makeSurveyAnswer(id1, questionId = "Q1", answer = "UPDATED")))

        assertEquals("session1 must have 1 updated row", 1, dao.getSurveyAnswersForSession(id1).size)
        assertEquals("session2 must be untouched", 1, dao.getSurveyAnswersForSession(id2).size)
        assertEquals("session2 answer must still be A2", "A2", dao.getSurveyAnswersForSession(id2)[0].answer)
    }
}
