package com.mmg.manahub.feature.home.presentation

import com.mmg.manahub.R

/**
 * Categorization for the Home dashboard's Rules Tip catalog (Home feature overhaul Phase 2.4).
 *
 * Each category has a short, English display label resolved from [labelRes] — never hardcoded
 * (F-11). Order here is purely a presentation grouping; it has no bearing on daily selection.
 */
enum class TipCategory(val labelRes: Int) {
    FUNDAMENTALS(R.string.tip_category_fundamentals),
    STACK_TIMING(R.string.tip_category_stack_timing),
    COMBAT(R.string.tip_category_combat),
    KEYWORDS(R.string.tip_category_keywords),
    GAME_STATE(R.string.tip_category_game_state),
    COMMANDER(R.string.tip_category_commander),
    TOKENS_COUNTERS(R.string.tip_category_tokens_counters),
    DECKBUILDING(R.string.tip_category_deckbuilding),
    MODERN_MECHANICS(R.string.tip_category_modern_mechanics),
}

/**
 * A single daily rules tip. [body] may contain inline mana/tap symbol syntax (`{T}`, `{W}`,
 * `{2}`, `{C}`, …) — [RulesTipWidget] renders it through [com.mmg.manahub.core.ui.components.OracleText],
 * which turns that syntax into icons.
 */
data class RuleTip(
    val title: String,
    val body: String,
    val category: TipCategory,
    val stableId: String = "",
    val references: List<String> = emptyList(),
    val query: String = "",
)

/**
 * The full Rules Tip catalog (Home feature overhaul Phase 2.4).
 *
 * Merges the original 62 tips (each fact-checked and assigned a category; near-duplicates of the
 * richer Appendix A tips below were dropped rather than kept side-by-side with a redundant
 * restatement) with the ~110-tip Appendix A catalog from the overhaul plan doc, verified against
 * the Comprehensive Rules current as of late 2025. The MODERN_MECHANICS entries were additionally
 * spot-checked against live rulings/reminder text for the three least-familiar mechanics
 * (Mobilize, Station, Harmonize) before shipping, per the accuracy-gate requirement.
 *
 * Deliberately NOT padded to hit a round number — every entry here earns its place with a
 * non-redundant insight. Current size is documented in [MTG_TIPS_CATALOG]'s call site
 * (`RulesTipWidget`); a future catalog test should assert against the real count rather than an
 * assumed one.
 */
val MTG_TIPS_CATALOG: List<RuleTip> = buildList {
    // ═══════════════════════════════════════════════════════════════════════
    //  FUNDAMENTALS
    // ═══════════════════════════════════════════════════════════════════════
    add(RuleTip("One land per turn", "You may play one land per turn, only during one of your main phases, only when the stack is empty. Playing a land doesn't use the stack, so it can't be responded to.", TipCategory.FUNDAMENTALS, stableId = "rules_tip_fundamentals_playing_lands", references = listOf(), query = "playing lands"))
    add(RuleTip("Mana doesn't carry over", "Your mana pool empties at the end of every step and phase, not just at the end of the turn. Floating mana from your upkeep is gone by your draw step.", TipCategory.FUNDAMENTALS, stableId = "rules_tip_fundamentals_unspent_mana", references = listOf("106.4", "500.5"), query = "unspent mana"))
    add(RuleTip("Two main phases", "You have a main phase before and after combat. Casting sorceries after combat often gives you more information about how the turn went.", TipCategory.FUNDAMENTALS, stableId = "rules_tip_fundamentals_main_phase", references = listOf(), query = "main phase"))
    add(RuleTip("The untap step is silent", "No player receives priority during the untap step. Abilities that trigger \"at the beginning of your untap step\" actually wait and go on the stack during upkeep.", TipCategory.FUNDAMENTALS, stableId = "rules_tip_fundamentals_untap_step", references = listOf(), query = "untap step"))
    add(RuleTip("Summoning sickness, precisely", "A creature you haven't controlled since your turn began can't attack or use abilities with {T} or {Q} in the cost. It can still block and use all its other abilities.", TipCategory.FUNDAMENTALS, stableId = "rules_tip_fundamentals_302_6", references = listOf(), query = "302.6"))
    add(RuleTip("Tapped creatures still bite", "A tapped creature can't block, but it deals and receives combat damage normally, and its static abilities keep working.", TipCategory.FUNDAMENTALS, stableId = "rules_tip_fundamentals_tapped_attacking_blocking", references = listOf(), query = "tapped attacking blocking"))
    add(RuleTip("First player skips a draw — sometimes", "In a two-player game, the starting player skips their first draw step. In Two-Headed Giant, the starting team skips it. In other multiplayer games, including multiplayer Commander, no player skips that first draw step.", TipCategory.FUNDAMENTALS, stableId = "rules_tip_fundamentals_starting_player_draw_step", references = listOf("103.8a", "103.8b", "103.8c"), query = "starting player draw step"))
    add(RuleTip("The London mulligan", "For each mulligan, shuffle your hand into your library, draw your starting hand size, then bottom one card per counted mulligan. In multiplayer games and all Brawl games, the first mulligan does not count toward the cards put on the bottom.", TipCategory.FUNDAMENTALS, stableId = "rules_tip_fundamentals_mulligan", references = listOf("103.5", "103.5c"), query = "mulligan"))
    add(RuleTip("Maximum hand size", "You only discard down to seven during your own cleanup step. During the turn you can hold any number of cards.", TipCategory.FUNDAMENTALS, stableId = "rules_tip_fundamentals_maximum_hand_size", references = listOf(), query = "maximum hand size"))
    add(RuleTip("Cast vs. play", "You \"cast\" spells and \"play\" lands. Effects that care about casting (like storm or magecraft) never trigger from playing a land.", TipCategory.FUNDAMENTALS, stableId = "rules_tip_fundamentals_casting_spells_playing_lands", references = listOf(), query = "casting spells playing lands"))
    add(RuleTip("Beginning of combat matters", "\"Beginning of combat\" is a step before attackers are declared. It's your last window to tap down a creature you fear will attack.", TipCategory.FUNDAMENTALS, stableId = "rules_tip_fundamentals_beginning_of_combat_step", references = listOf(), query = "beginning of combat step"))
    add(RuleTip("Three ways to lose", "As state-based actions, you normally lose at 0 or less life, after attempting to draw from an empty library, or with ten poison counters. Two-Headed Giant instead uses a team poison total of fifteen. Cards and variant rules can create exceptions.", TipCategory.FUNDAMENTALS, stableId = "rules_tip_fundamentals_stateminusbased_actions_losing", references = listOf("704.5a", "704.5b", "704.5c", "810.8d"), query = "state-based actions losing"))
    add(RuleTip("Mana Burn is gone", "Mana burn was removed in Magic 2010. Unused mana in your mana pool at end of step or phase simply disappears — it doesn't cause damage.", TipCategory.FUNDAMENTALS, stableId = "rules_tip_fundamentals_mana_burn_absent", references = listOf(), query = "unspent mana"))
    add(RuleTip("Colorless vs. Generic", "Generic mana ({1}, {2}) can be paid by any mana. Colorless mana ({C}) can ONLY be paid by colorless sources — they're different!", TipCategory.FUNDAMENTALS, stableId = "rules_tip_fundamentals_colorless_generic_mana", references = listOf(), query = "colorless generic mana"))

    // ═══════════════════════════════════════════════════════════════════════
    //  STACK_TIMING
    // ═══════════════════════════════════════════════════════════════════════
    add(RuleTip("Last in, first out", "The stack resolves top-down: the most recently cast spell resolves first. \"In response\" always means going on top.", TipCategory.STACK_TIMING, stableId = "rules_tip_stack_timing_stack_resolving", references = listOf(), query = "stack resolving"))
    add(RuleTip("Priority passes for everything", "Every spell and every non-mana ability waits on the stack while each player gets a chance to respond before it resolves.", TipCategory.STACK_TIMING, stableId = "rules_tip_stack_timing_priority", references = listOf(), query = "priority"))
    add(RuleTip("Mana abilities are instant-instant", "Tapping a land or creature for mana doesn't use the stack and can't be responded to or countered.", TipCategory.STACK_TIMING, stableId = "rules_tip_stack_timing_mana_abilities", references = listOf(), query = "mana abilities"))
    add(RuleTip("Triggers are mandatory", "A triggered ability triggers when its condition is met, even if its effect says \"you may.\" The ability goes on the stack normally; you choose whether to perform the optional action when it resolves.", TipCategory.STACK_TIMING, stableId = "rules_tip_stack_timing_optional_triggered_abilities", references = listOf("603.5"), query = "optional triggered abilities"))
    add(RuleTip("Targets lock at cast time", "You choose targets when you cast a spell, not when it resolves. If every target is illegal by resolution, the spell \"fizzles\" — it does nothing at all, not even its untargeted parts.", TipCategory.STACK_TIMING, stableId = "rules_tip_stack_timing_illegal_targets", references = listOf(), query = "illegal targets"))
    add(RuleTip("Counter wars", "A counterspell on the stack is itself a spell: it can be countered in response.", TipCategory.STACK_TIMING, stableId = "rules_tip_stack_timing_counter_spells", references = listOf(), query = "counter spells"))
    add(RuleTip("Kill the ability's source? Too late", "Once an ability is on the stack, it resolves even if its source leaves the battlefield. Sacrificing a creature in response to removal still gets you its activated ability.", TipCategory.STACK_TIMING, stableId = "rules_tip_stack_timing_source_ability_independent", references = listOf(), query = "source ability independent"))
    add(RuleTip("You can respond to yourself", "After casting a spell you may hold priority and cast another one in response to your own spell — useful to sneak a pump spell under expected removal.", TipCategory.STACK_TIMING, stableId = "rules_tip_stack_timing_priority_casting", references = listOf(), query = "priority casting"))
    add(RuleTip("APNAP order", "When several players must act or put triggers on the stack simultaneously, the Active Player acts first, then Non-Active Players in turn order. Later triggers resolve first.", TipCategory.STACK_TIMING, stableId = "rules_tip_stack_timing_active_player_nonactive_player_order", references = listOf(), query = "active player nonactive player order"))
    add(RuleTip("You order your own triggers", "If several of your abilities trigger at the same time, you choose the order they go on the stack — so you choose the order they resolve, last-added first.", TipCategory.STACK_TIMING, stableId = "rules_tip_stack_timing_simultaneous_triggered_abilities", references = listOf(), query = "simultaneous triggered abilities"))
    add(RuleTip("\"Can't be countered\" isn't \"can't be answered\"", "You can still respond to an uncounterable spell: remove its target and it fizzles anyway.", TipCategory.STACK_TIMING, stableId = "rules_tip_stack_timing_uncounterable_illegal_targets", references = listOf(), query = "illegal targets"))
    add(RuleTip("Flash means anytime", "Flash lets you cast a spell whenever you could cast an instant — during combat, on an opponent's turn, or in response to another spell.", TipCategory.STACK_TIMING, stableId = "rules_tip_stack_timing_flash", references = listOf(), query = "flash"))
    add(RuleTip("Split second freezes the game", "While a split-second spell is on the stack, players can't cast spells or activate non-mana abilities. Triggered abilities and mana abilities still work.", TipCategory.STACK_TIMING, stableId = "rules_tip_stack_timing_split_second", references = listOf(), query = "split second"))
    add(RuleTip("Copies aren't cast", "A copy of a spell is put onto the stack, not cast, so cast-triggers like prowess or storm don't see it. Magecraft is the exception: it counts copies too.", TipCategory.STACK_TIMING, stableId = "rules_tip_stack_timing_copy_spell", references = listOf(), query = "copy spell"))

    // ═══════════════════════════════════════════════════════════════════════
    //  COMBAT
    // ═══════════════════════════════════════════════════════════════════════
    add(RuleTip("Attack players, not creatures", "You declare attacks against a player, a planeswalker, or a battle — never against a creature. Blocking is how creatures meet.", TipCategory.COMBAT, stableId = "rules_tip_combat_declare_attackers", references = listOf(), query = "declare attackers"))
    add(RuleTip("Attackers tap on declaration", "Declaring a creature as an attacker normally taps it unless it has vigilance. After it attacks, you can still activate its abilities if you can pay their costs; vigilance can let an attacking creature use a {T} ability before damage.", TipCategory.COMBAT, stableId = "rules_tip_combat_declaring_attackers_vigilance", references = listOf("508.1f", "117.1b", "702.20b"), query = "declaring attackers vigilance"))
    add(RuleTip("Blocking is free", "Blockers don't tap to block. A tapped creature simply can't be declared as a blocker.", TipCategory.COMBAT, stableId = "rules_tip_combat_declare_blockers", references = listOf(), query = "declare blockers"))
    add(RuleTip("Blocked stays blocked", "If the only blocker is destroyed before damage, the attacker is still blocked and deals no combat damage — unless it has trample.", TipCategory.COMBAT, stableId = "rules_tip_combat_blocked_creature", references = listOf(), query = "blocked creature"))
    add(RuleTip("Trample math", "A trampler only needs to assign lethal damage to its blockers; the rest hits the player. With deathtouch, \"lethal\" is just 1 per blocker — the rest tramples through.", TipCategory.COMBAT, stableId = "rules_tip_combat_trample_deathtouch", references = listOf(), query = "trample deathtouch"))
    add(RuleTip("First strike is a whole extra step", "First-strike and double-strike damage happens in its own combat damage step. A creature killed by first strike never gets to deal its damage.", TipCategory.COMBAT, stableId = "rules_tip_combat_first_strike_combat_damage", references = listOf(), query = "first strike combat damage"))
    add(RuleTip("Double strike hits twice", "A creature with double strike can deal damage in both combat damage steps. A pump spell before the first step can boost both hits; a pump between steps boosts only the second. A blocked double striker still needs a blocker to damage, unless it has trample.", TipCategory.COMBAT, stableId = "rules_tip_combat_double_strike", references = listOf("702.4b", "510.1c", "702.19b"), query = "double strike"))
    add(RuleTip("Multiple blockers, flexible damage", "When multiple creatures block one attacker, its controller divides combat damage among them as they choose. There is no damage-assignment order. Trample still requires lethal damage assigned to every blocker before damage can reach the attacked player, planeswalker, or battle.", TipCategory.COMBAT, stableId = "rules_tip_combat_510_1c", references = listOf("510.1c", "702.19b"), query = "510.1c"))
    add(RuleTip("Vigilance keeps options open", "A vigilant attacker stays untapped, so it can still block on the way back or use its {T} abilities after combat.", TipCategory.COMBAT, stableId = "rules_tip_combat_vigilance", references = listOf(), query = "vigilance"))
    add(RuleTip("Menace needs a crowd", "A creature with menace can't be blocked by exactly one creature — it's two blockers or none.", TipCategory.COMBAT, stableId = "rules_tip_combat_menace", references = listOf(), query = "menace"))
    add(RuleTip("The best trick window", "The strongest moment for a combat trick is after blockers are declared but before damage: your opponent has committed and can no longer change blocks.", TipCategory.COMBAT, stableId = "rules_tip_combat_declare_blockers_priority", references = listOf(), query = "declare blockers priority"))
    add(RuleTip("Attack triggers stick", "\"Whenever this creature attacks\" triggers the moment attackers are declared. Removing the attacker afterward doesn't undo the trigger.", TipCategory.COMBAT, stableId = "rules_tip_combat_attacks_triggered_ability", references = listOf(), query = "attacks triggered ability"))
    add(RuleTip("Indestructible isn't invincible", "Indestructible creatures still take damage, can be blocked, and die to sacrifice effects or -X/-X. Only \"destroy\" and lethal damage bounce off.", TipCategory.COMBAT, stableId = "rules_tip_combat_indestructible", references = listOf(), query = "indestructible"))
    add(RuleTip("Fight isn't combat", "Fight and \"bite\" effects deal damage outside combat: first strike does nothing there, but deathtouch and lifelink apply in full.", TipCategory.COMBAT, stableId = "rules_tip_combat_fight", references = listOf(), query = "fight"))
    add(RuleTip("Removing an attacker mid-combat", "Killing an attacking creature before the damage step prevents all its combat damage — even if it has already triggered its attack abilities.", TipCategory.COMBAT, stableId = "rules_tip_combat_removed_from_combat", references = listOf(), query = "removed from combat"))
    add(RuleTip("Blocking legality has no size limit", "Power and toughness alone do not restrict blocking: a 0/1 can block a 10/10. The blocker must be untapped, and flying, menace, protection, or other restrictions may still make the block illegal.", TipCategory.COMBAT, stableId = "rules_tip_combat_blocking_restrictions", references = listOf("509.1a", "509.1b"), query = "blocking restrictions"))

    // ═══════════════════════════════════════════════════════════════════════
    //  KEYWORDS (evergreen & common abilities)
    // ═══════════════════════════════════════════════════════════════════════
    add(RuleTip("Hexproof vs. shroud", "Hexproof: your opponents can't target it, but you still can. Shroud: nobody can target it, including you.", TipCategory.KEYWORDS, stableId = "rules_tip_keywords_hexproof_shroud", references = listOf(), query = "hexproof shroud"))
    add(RuleTip("Ward is a toll, not a wall", "Ward does not stop targeting. When a permanent with ward becomes the target of an opponent's spell or ability, ward triggers and counters that spell or ability unless that opponent pays the ward cost. Players may respond to the ward trigger.", TipCategory.KEYWORDS, stableId = "rules_tip_keywords_ward", references = listOf("702.21a"), query = "ward"))
    add(RuleTip("Protection = DEBT", "Protection from a quality prevents matching damage, targeting, enchanting/equipping, and blocking. A nontargeting destroy-all effect can still destroy the permanent, but protection can prevent damage from a matching damage-based board wipe.", TipCategory.KEYWORDS, stableId = "rules_tip_keywords_protection", references = listOf("702.16b", "702.16c", "702.16d", "702.16e", "702.16f"), query = "protection"))
    add(RuleTip("Lifelink has no gap", "Lifelink life gain happens at the same time as the damage — there's no window to kill a player \"before the lifelink resolves\", since it isn't a separate trigger. It does matter for effects that trigger specifically on life gain, though.", TipCategory.KEYWORDS, stableId = "rules_tip_keywords_lifelink", references = listOf(), query = "lifelink"))
    add(RuleTip("Haste, fully", "Haste removes summoning sickness entirely: the creature can attack AND use its {T} abilities the turn it arrives.", TipCategory.KEYWORDS, stableId = "rules_tip_keywords_haste", references = listOf(), query = "haste"))
    add(RuleTip("Flying meets Reach", "Flying creatures can only be blocked by creatures with flying or reach — don't forget your reach creatures can block fliers too, even though they can't fly themselves.", TipCategory.KEYWORDS, stableId = "rules_tip_keywords_flying_reach", references = listOf(), query = "flying reach"))
    add(RuleTip("Deathtouch scales down", "Any nonzero damage from a source with deathtouch causes a creature with positive toughness to be destroyed at the next state-based-action check. Indestructible, regeneration, or prevention can save it. Deathtouch also makes one assigned combat damage count as lethal for trample.", TipCategory.KEYWORDS, stableId = "rules_tip_keywords_deathtouch", references = listOf("702.2b", "702.2c", "702.12b"), query = "deathtouch"))
    add(RuleTip("Prowess counts casts", "Prowess triggers when you cast a noncreature spell — copies put on the stack by other effects don't trigger it.", TipCategory.KEYWORDS, stableId = "rules_tip_keywords_prowess", references = listOf(), query = "prowess"))
    add(RuleTip("Equip at sorcery speed", "Equip abilities can only be activated during your main phase with an empty stack. If the equipped creature dies, the Equipment survives, unattached.", TipCategory.KEYWORDS, stableId = "rules_tip_keywords_equip", references = listOf(), query = "equip"))
    add(RuleTip("Auras target on the way in", "Casting an Aura targets, so hexproof stops it. But an Aura put onto the battlefield by an effect doesn't target and can land on anything legal.", TipCategory.KEYWORDS, stableId = "rules_tip_keywords_aura_target", references = listOf(), query = "Aura target"))
    add(RuleTip("Defender still defends", "A creature with defender can't attack, but it blocks, triggers, and uses abilities like any other creature.", TipCategory.KEYWORDS, stableId = "rules_tip_keywords_defender", references = listOf(), query = "defender"))
    add(RuleTip("Kicker is part of casting", "Kicker costs are paid as you cast the spell. It's still one spell — countering it counters the kicked version too.", TipCategory.KEYWORDS, stableId = "rules_tip_keywords_kicker", references = listOf(), query = "kicker"))
    add(RuleTip("Cycling dodges counterspells", "Cycling is an activated ability, not a spell. A counterspell can't stop it; only effects that counter abilities can. It can also be activated at instant speed — you discard first, then draw, which can feed graveyard synergies.", TipCategory.KEYWORDS, stableId = "rules_tip_keywords_cycling", references = listOf(), query = "cycling"))
    add(RuleTip("Landfall counts every land", "Landfall abilities trigger when a land enters under your control, whether played or put there by an effect. A fetch land can produce one trigger when it enters and another when its fetched land enters, even during the same turn.", TipCategory.KEYWORDS, stableId = "rules_tip_keywords_land_enters_triggered_abilities", references = listOf("603.2", "603.6a"), query = "land enters triggered abilities"))
    add(RuleTip("Regenerate is a pre-paid shield", "A regeneration shield must exist before destruction happens. When it replaces destruction, remove all damage marked on the permanent, tap it, and remove it from combat if it is attacking or blocking. Some static abilities provide regeneration without an activation.", TipCategory.KEYWORDS, stableId = "rules_tip_keywords_regenerate", references = listOf("701.19a", "701.19b"), query = "regenerate"))
    add(RuleTip("Phasing", "Phased-out permanents are treated as if they don't exist. Auras and Equipment attached to them phase out too, and phase back in together.", TipCategory.KEYWORDS, stableId = "rules_tip_keywords_phasing", references = listOf(), query = "phasing"))
    add(RuleTip("Cascade", "Cascade triggers when you cast the spell. Exile cards until you find a nonland card with lower mana value, then you may cast it without paying its mana cost if the resulting spell also has lower mana value. Casting happens during the trigger's resolution, regardless of normal sorcery timing.", TipCategory.KEYWORDS, stableId = "rules_tip_keywords_cascade", references = listOf("702.85a"), query = "cascade"))
    add(RuleTip("Morph", "A morphed card is normally a face-down 2/2 colorless creature with no name, subtypes, abilities, or mana cost. With priority, you may pay its morph cost to turn it face up as a special action; opponents cannot respond to that action.", TipCategory.KEYWORDS, stableId = "rules_tip_keywords_morph", references = listOf("702.37a", "702.37e"), query = "morph"))
    add(RuleTip("Storm", "Storm copies the spell for each spell cast before it this turn. Rituals and cantrips earlier in the turn all count!", TipCategory.KEYWORDS, stableId = "rules_tip_keywords_storm", references = listOf(), query = "storm"))
    add(RuleTip("Flashback", "Flashback lets you cast a spell from the graveyard by paying its flashback cost. The spell is then exiled, not returned to the graveyard.", TipCategory.KEYWORDS, stableId = "rules_tip_keywords_flashback", references = listOf(), query = "flashback"))
    add(RuleTip("Dredge", "If you have at least N cards in your library, dredge N can replace a draw: mill N cards and return the card with dredge from your graveyard to your hand. You cannot choose dredge N with fewer than N cards remaining.", TipCategory.KEYWORDS, stableId = "rules_tip_keywords_dredge", references = listOf("702.52a"), query = "dredge"))
    add(RuleTip("Delve", "You can exile any number of cards from your graveyard when paying for Delve — each exiled card pays for {1} of generic mana.", TipCategory.KEYWORDS, stableId = "rules_tip_keywords_delve", references = listOf(), query = "delve"))
    add(RuleTip("Convoke", "Convoke lets you tap untapped creatures you control to pay for a spell: each pays for one generic mana or one mana of its color. This does not produce mana, and summoning-sick creatures can convoke. An ability having {T} in its cost does not automatically make it a mana ability.", TipCategory.KEYWORDS, stableId = "rules_tip_keywords_convoke", references = listOf("702.51a", "605.1a", "302.6"), query = "convoke"))
    add(RuleTip("Suspend", "Suspending a card means paying its suspend cost to exile it from your hand with time counters; this special action is not casting a spell. Remove a counter at the beginning of your upkeep. When the last is removed, you may play the card without paying its mana cost if able.", TipCategory.KEYWORDS, stableId = "rules_tip_keywords_suspend", references = listOf("702.62a"), query = "suspend"))
    add(RuleTip("Escape", "Escape lets you recast cards from the graveyard by paying the escape cost and exiling a set number of other graveyard cards.", TipCategory.KEYWORDS, stableId = "rules_tip_keywords_escape", references = listOf(), query = "escape"))
    add(RuleTip("Foretell", "During your own turn, whenever you have priority, you may pay {2} to exile a card with foretell from your hand face down. On a later turn, you may cast it for its foretell cost, following its normal timing restrictions.", TipCategory.KEYWORDS, stableId = "rules_tip_keywords_foretell", references = listOf("702.143a", "702.143b"), query = "foretell"))
    add(RuleTip("Boast", "Boast abilities can only be activated once per turn, and only if the creature attacked this turn. They're not tap abilities.", TipCategory.KEYWORDS, stableId = "rules_tip_keywords_boast", references = listOf(), query = "boast"))
    add(RuleTip("Sagas", "Sagas trigger on your precombat main phase. Chapter I triggers when it enters, subsequent chapters on later turns. The saga sacrifices itself after the final chapter.", TipCategory.KEYWORDS, stableId = "rules_tip_keywords_sagas", references = listOf(), query = "sagas"))
    add(RuleTip("MDFCs", "When playing a modal double-faced card, choose the face you will use. A land face is played as a land; a spell face can be cast, including a back face. Apply the timing and permissions for the chosen face.", TipCategory.KEYWORDS, stableId = "rules_tip_keywords_modal_doubleminusfaced_cards", references = listOf("712.11b", "712.12"), query = "modal double-faced cards"))
    add(RuleTip("Split Cards", "Outside the stack, a split card has the combined characteristics of both halves, including their combined mana value. On the stack, only the chosen half counts, unless both halves were cast using fuse.", TipCategory.KEYWORDS, stableId = "rules_tip_keywords_split_cards", references = listOf("709.3b", "709.4", "709.4d"), query = "split cards"))
    add(RuleTip("Adventures", "Adventure cards can be cast as the Adventure (exile it), then cast the creature later from exile. While in exile, it's still a card you own.", TipCategory.KEYWORDS, stableId = "rules_tip_keywords_adventures", references = listOf(), query = "adventures"))

    // ═══════════════════════════════════════════════════════════════════════
    //  GAME_STATE (state-based actions & zones)
    // ═══════════════════════════════════════════════════════════════════════
    add(RuleTip("The invisible referee", "State-based actions (creatures dying to damage or 0 toughness, players losing at 0 life, legends clashing) are checked automatically whenever a player would get priority. Nobody can respond to them.", TipCategory.GAME_STATE, stableId = "rules_tip_game_state_stateminusbased_actions", references = listOf(), query = "state-based actions"))
    add(RuleTip("Zero toughness can't be saved", "A creature with toughness 0 or less is put into the graveyard by the rules, not destroyed — regeneration and indestructible don't help.", TipCategory.GAME_STATE, stableId = "rules_tip_game_state_toughness_zero", references = listOf(), query = "toughness zero"))
    add(RuleTip("-X/-X beats indestructible", "Reducing toughness to 0 isn't destruction, so it kills indestructible creatures. Damage never can.", TipCategory.GAME_STATE, stableId = "rules_tip_game_state_indestructible_toughness", references = listOf(), query = "indestructible toughness"))
    add(RuleTip("The legend rule, per player", "If you control two or more legendary permanents with the same name, choose one and put the rest into their owners' graveyards. Opponents' copies do not count. This is not destruction; a creature put into a graveyard this way dies.", TipCategory.GAME_STATE, stableId = "rules_tip_game_state_legend_rule", references = listOf("704.5j", "700.4"), query = "legend rule"))
    add(RuleTip("Counters cancel out", "+1/+1 and -1/-1 counters on the same permanent are removed in pairs automatically.", TipCategory.GAME_STATE, stableId = "rules_tip_game_state_plus1_plus1_minus1_minus1_counters", references = listOf(), query = "+1/+1 -1/-1 counters"))
    add(RuleTip("Tokens vanish, but they die first", "A creature token going from the battlefield to a graveyard triggers dies abilities, then ceases to exist when state-based actions are checked. A token moved to exile or hand does not die, and a token that leaves the battlefield cannot return.", TipCategory.GAME_STATE, stableId = "rules_tip_game_state_token_leaves_battlefield", references = listOf("704.5d", "111.8", "700.4"), query = "token leaves battlefield"))
    add(RuleTip("Clones copy the print", "A copy effect copies the printed characteristics (plus other copy effects) — not counters, damage, Auras, or Equipment on the original.", TipCategory.GAME_STATE, stableId = "rules_tip_game_state_copiable_values", references = listOf(), query = "copiable values"))
    add(RuleTip("Empty library isn't loss — drawing is", "You only lose when you attempt to draw from an empty library. Sitting at zero cards is safe until someone makes you draw.", TipCategory.GAME_STATE, stableId = "rules_tip_game_state_empty_library_draw", references = listOf(), query = "empty library draw"))
    add(RuleTip("Spells finish resolving first", "State-based actions wait until a spell has fully resolved. Your life can dip to 0 mid-resolution and come back up before the game ever checks.", TipCategory.GAME_STATE, stableId = "rules_tip_game_state_stateminusbased_actions_resolving", references = listOf(), query = "state-based actions resolving"))
    add(RuleTip("Sacrifice pierces everything", "Sacrificing is neither destruction nor targeting: indestructible, hexproof, and protection are all useless against \"each player sacrifices a creature.\"", TipCategory.GAME_STATE, stableId = "rules_tip_game_state_sacrifice", references = listOf(), query = "sacrifice"))
    add(RuleTip("Exile isn't dying", "\"Dies\" means going to the graveyard from the battlefield. Exiling a creature triggers no death triggers — which is exactly why exile removal is prized.", TipCategory.GAME_STATE, stableId = "rules_tip_game_state_dies_exile", references = listOf(), query = "dies exile"))
    add(RuleTip("Copying a spell isn't casting it", "A copy of a spell is put directly onto the stack — it was never cast. Effects that trigger \"whenever you cast a spell\" won't see it.", TipCategory.GAME_STATE, stableId = "rules_tip_game_state_spell_copy_cast", references = listOf(), query = "spell copy cast"))

    // ═══════════════════════════════════════════════════════════════════════
    //  COMMANDER
    // ═══════════════════════════════════════════════════════════════════════
    add(RuleTip("Commander tax", "Casting your commander from the command zone costs {2} more for each previous time you've cast it from there. The tax never resets during the game.", TipCategory.COMMANDER, stableId = "rules_tip_commander_commander_tax", references = listOf("903.8"), query = "commander tax"))
    add(RuleTip("21 means dead", "A player who has taken 21 or more combat damage from the same commander over the course of the game loses. It's tracked per commander, and only combat damage counts.", TipCategory.COMMANDER, stableId = "rules_tip_commander_903_10a", references = listOf("903.10a"), query = "903.10a"))
    add(RuleTip("Your commander can still \"die\"", "If your commander goes to the graveyard or exile, death and exile triggers see it there first; then, when state-based actions are checked, you may move it to the command zone.", TipCategory.COMMANDER, stableId = "rules_tip_commander_903_9a", references = listOf("903.9a"), query = "903.9a"))
    add(RuleTip("Hand and library are different", "If your commander would go to your hand or library, you choose to send it to the command zone as a replacement — it never reaches that zone at all.", TipCategory.COMMANDER, stableId = "rules_tip_commander_903_9b", references = listOf("903.9b"), query = "903.9b"))
    add(RuleTip("Color identity is strict", "Color identity includes colored mana symbols in a card's mana cost and rules text, its color indicator, and characteristic-defining color abilities. Ignore reminder text, but include the back face and alternative characteristics. Hybrid {W/U} counts as both white and blue.", TipCategory.COMMANDER, stableId = "rules_tip_commander_color_identity", references = listOf("903.4", "903.4c", "903.4d", "903.4e"), query = "color identity"))
    add(RuleTip("Singleton, with exceptions", "One copy of each card except basic lands — and cards whose own text says \"a deck can have any number,\" which override the rule.", TipCategory.COMMANDER, stableId = "rules_tip_commander_commander_deck_construction", references = listOf(), query = "Commander deck construction"))
    add(RuleTip("Partners split the seat", "Two partner commanders start in the command zone together, the deck drops to 98, color identity is their union, and each one tracks its own tax and its own 21 commander damage.", TipCategory.COMMANDER, stableId = "rules_tip_commander_partner_commander", references = listOf(), query = "partner commander"))
    add(RuleTip("Stolen commanders still count", "Your commander is yours even while an opponent controls it — its combat damage still counts toward that commander's 21 against whoever it hits.", TipCategory.COMMANDER, stableId = "rules_tip_commander_commander_combat_damage", references = listOf("903.3", "903.10a"), query = "commander combat damage"))
    add(RuleTip("Command-zone casts are normal casts", "Casting a commander from the command zone follows normal timing and can be countered. If it is, you can send it back to the command zone and try again later — with more tax.", TipCategory.COMMANDER, stableId = "rules_tip_commander_commander_command_zone_cast", references = listOf(), query = "commander command zone cast"))
    add(RuleTip("The monarch", "The monarch draws an extra card at the beginning of their end step. Deal combat damage to the monarch and you steal the crown.", TipCategory.COMMANDER, stableId = "rules_tip_commander_monarch", references = listOf(), query = "monarch"))
    add(RuleTip("Goad forces the issue", "A goaded creature must attack each combat if able, and must attack someone other than the player who goaded it if possible.", TipCategory.COMMANDER, stableId = "rules_tip_commander_goad", references = listOf(), query = "goad"))
    add(RuleTip("When a player leaves", "When a player leaves a multiplayer game, objects they own leave with them and effects giving them control end. Their remaining spells and abilities on the stack that are not represented by cards cease to exist; objects still controlled by them are exiled.", TipCategory.COMMANDER, stableId = "rules_tip_commander_player_leaves_game", references = listOf("800.4a"), query = "player leaves game"))
    add(RuleTip("Poison ignores the 40", "Ten poison counters kill a Commander player just like anyone else — the 40 starting life doesn't help against infect or toxic.", TipCategory.COMMANDER, stableId = "rules_tip_commander_poison_commander", references = listOf(), query = "poison Commander"))
    add(RuleTip("Politics is a resource", "In multiplayer, threat assessment beats raw power: the player who looks the scariest eats the removal. Table talk, deals, and timing are part of the game.", TipCategory.COMMANDER, stableId = "rules_tip_commander_multiplayer", references = listOf(), query = "multiplayer"))

    // ═══════════════════════════════════════════════════════════════════════
    //  TOKENS_COUNTERS (tokens, counters & card economy)
    // ═══════════════════════════════════════════════════════════════════════
    add(RuleTip("Treasure is more than mana", "A Treasure is \"{T}, Sacrifice this artifact: Add one mana of any color.\" It's also an artifact sitting on the battlefield: it counts for affinity and metalcraft, and it can be stolen or destroyed like any other permanent.", TipCategory.TOKENS_COUNTERS, stableId = "rules_tip_tokens_counters_treasure_token", references = listOf(), query = "Treasure token"))
    add(RuleTip("Food, Clue, Blood, Map", "Food: {2}, {T}, sacrifice to gain 3 life. Clue: {2}, sacrifice to draw. Blood: {1}, {T}, discard a card, sacrifice to draw. Map: {1}, {T}, sacrifice to make a target creature you control explore; activate only as a sorcery.", TipCategory.TOKENS_COUNTERS, stableId = "rules_tip_tokens_counters_predefined_tokens", references = listOf("111.10b", "111.10f", "111.10g", "111.10s"), query = "predefined tokens"))
    add(RuleTip("Powerstones are picky", "A Powerstone taps for {C}, but that mana can't be spent to cast a nonartifact spell. Activating abilities is fine.", TipCategory.TOKENS_COUNTERS, stableId = "rules_tip_tokens_counters_powerstone_token", references = listOf(), query = "Powerstone token"))
    add(RuleTip("Token copies are the real thing", "A token copy of a legendary creature is still legendary — make a copy of your own legend and the legend rule bites immediately.", TipCategory.TOKENS_COUNTERS, stableId = "rules_tip_tokens_counters_legend_rule_token", references = listOf(), query = "legend rule token"))
    add(RuleTip("Stun counters", "A permanent with a stun counter doesn't untap as normal; instead, one stun counter is removed. Vigilance sidesteps them entirely on the attack.", TipCategory.TOKENS_COUNTERS, stableId = "rules_tip_tokens_counters_stun_counters", references = listOf(), query = "stun counters"))
    add(RuleTip("Shield counters", "A shield counter replaces destruction from an effect or prevents damage by removing a shield counter. Exile, sacrifice, and reducing toughness to 0 still work. Unpreventable damage can still be dealt despite the shield's prevention effect.", TipCategory.TOKENS_COUNTERS, stableId = "rules_tip_tokens_counters_shield_counters", references = listOf("122.1c", "615.12"), query = "shield counters"))
    add(RuleTip("Keyword counters are permanent", "Flying, first strike, or deathtouch counters grant the ability for as long as the counter stays — they survive end of turn, unlike most pump spells.", TipCategory.TOKENS_COUNTERS, stableId = "rules_tip_tokens_counters_keyword_counters", references = listOf(), query = "keyword counters"))
    add(RuleTip("Infect vs. toxic", "Infect replaces its damage: -1/-1 counters on creatures, poison on players. Toxic deals normal damage AND gives poison counters on top.", TipCategory.TOKENS_COUNTERS, stableId = "rules_tip_tokens_counters_infect_toxic", references = listOf(), query = "infect toxic"))
    add(RuleTip("Loyalty is sorcery-paced", "Normally, activate a loyalty ability only with priority during your main phase while the stack is empty. Each permanent can have only one loyalty ability activated per turn, even if control changes; card effects can modify these restrictions.", TipCategory.TOKENS_COUNTERS, stableId = "rules_tip_tokens_counters_loyalty_ability", references = listOf("606.3"), query = "loyalty ability"))
    add(RuleTip("Attacking planeswalkers", "Combat damage dealt to a planeswalker removes that many loyalty counters. At zero loyalty it's gone — state-based, no response.", TipCategory.TOKENS_COUNTERS, stableId = "rules_tip_tokens_counters_planeswalker_damage_loyalty", references = listOf(), query = "planeswalker damage loyalty"))
    add(RuleTip("Counters survive blinking? No.", "Exiling a permanent and returning it makes it a new object: all counters, damage, and attachments are gone, and summoning sickness is back.", TipCategory.TOKENS_COUNTERS, stableId = "rules_tip_tokens_counters_new_object_zone", references = listOf(), query = "new object zone"))
    add(RuleTip("Proliferate picks per permanent", "Proliferate lets you add one counter of each kind already on any number of chosen permanents and players — poison, loyalty, +1/+1, charge, all of them.", TipCategory.TOKENS_COUNTERS, stableId = "rules_tip_tokens_counters_proliferate", references = listOf(), query = "proliferate"))
    add(RuleTip("Undergrowth counts cards, not tokens", "Undergrowth counts creature CARDS in your graveyard — not tokens (they cease to exist when they leave the battlefield, so they never sit in the graveyard to be counted).", TipCategory.TOKENS_COUNTERS, stableId = "rules_tip_tokens_counters_creature_card_token", references = listOf(), query = "creature card token"))
    add(RuleTip("Afterlife", "Afterlife X creates X 1/1 white and black flying Spirit tokens when the creature dies. Each token has flying.", TipCategory.TOKENS_COUNTERS, stableId = "rules_tip_tokens_counters_afterlife", references = listOf(), query = "afterlife"))
    add(RuleTip("Amass", "To amass a subtype, create a 0/0 black Army token of that subtype if you control no Army creature. Choose an Army you control, put the specified +1/+1 counters on it, and add that subtype. You can control multiple Armies.", TipCategory.TOKENS_COUNTERS, stableId = "rules_tip_tokens_counters_amass", references = listOf("701.47a"), query = "amass"))

    // ═══════════════════════════════════════════════════════════════════════
    //  DECKBUILDING (deckbuilding & strategy)
    // ═══════════════════════════════════════════════════════════════════════
    add(RuleTip("Play the minimum", "60 cards in constructed, 100 in Commander — exactly. Every card above the minimum lowers the odds of drawing your best cards.", TipCategory.DECKBUILDING, stableId = "rules_tip_deckbuilding_deck_construction", references = listOf(), query = "deck construction"))
    add(RuleTip("Respect the curve", "Count your deck's mana costs. If you can't reliably play something meaningful on turns two and three, the deck will lose games before its top-end matters.", TipCategory.DECKBUILDING, stableId = "rules_tip_deckbuilding_mana_cost", references = listOf(), query = "mana cost"))
    add(RuleTip("Land counts, rough guide", "About 17 lands in a 40-card limited deck, 22-26 in a 60-card deck depending on curve, and 36-38 (plus ramp) in Commander.", TipCategory.DECKBUILDING, stableId = "rules_tip_deckbuilding_lands_deck", references = listOf(), query = "lands deck"))
    add(RuleTip("The Commander trinity", "A rough baseline for a functional Commander deck: ~10 ramp pieces, ~10 card-draw effects, ~10 pieces of interaction/removal. Adjust, but never to zero.", TipCategory.DECKBUILDING, stableId = "rules_tip_deckbuilding_commander_deck", references = listOf(), query = "Commander deck"))
    add(RuleTip("Card advantage wins long games", "Every effect that trades one of your cards for two of your opponent's — or draws you two — compounds. The player with more cards usually wins the attrition war.", TipCategory.DECKBUILDING, stableId = "rules_tip_deckbuilding_drawing_cards", references = listOf(), query = "drawing cards"))
    add(RuleTip("Redundancy beats brilliance", "If your deck needs an effect to function, play functional duplicates of it. One copy of a combo piece is a prayer, not a plan.", TipCategory.DECKBUILDING, stableId = "rules_tip_deckbuilding_redundant_effects", references = listOf(), query = "deck construction"))
    add(RuleTip("Mulligan for function, not land count", "Keep hands that DO something in the first three turns. Four lands and three uncastable cards is a mulligan too.", TipCategory.DECKBUILDING, stableId = "rules_tip_deckbuilding_mulligan", references = listOf(), query = "mulligan"))
    add(RuleTip("Tempo vs. value", "Cheap interaction that stalls the opponent buys time (tempo); two-for-ones grind ahead (value). Know which one your deck wants and mulligan for it.", TipCategory.DECKBUILDING, stableId = "rules_tip_deckbuilding_priority", references = listOf(), query = "priority"))
    add(RuleTip("Sideboards answer, mainboards ask", "In best-of-three, the 15-card sideboard is for answers too narrow for game one. Build it against the decks you actually expect to face.", TipCategory.DECKBUILDING, stableId = "rules_tip_deckbuilding_sideboard", references = listOf(), query = "sideboard"))
    add(RuleTip("Removal isn't optional", "A deck that can't interact loses to the first strategy faster than its own. Even the most proactive deck wants a few cheap answers.", TipCategory.DECKBUILDING, stableId = "rules_tip_deckbuilding_destroy_exile", references = listOf(), query = "destroy exile"))
    add(RuleTip("Tutors still shuffle", "When searching your library, follow the effect's instructions, including shuffling if instructed. You still shuffle after failing to find a card if the effect tells you to shuffle; searching itself does not automatically require a shuffle.", TipCategory.DECKBUILDING, stableId = "rules_tip_deckbuilding_search_library", references = listOf("701.23"), query = "search library"))

    // ═══════════════════════════════════════════════════════════════════════
    //  MODERN_MECHANICS (2023-2026 mechanics)
    // ═══════════════════════════════════════════════════════════════════════
    add(RuleTip("Battles", "A Siege enters with defense counters and is protected by an opponent. Attack it and deal it damage to remove counters; when the last one is removed, its controller exiles it and casts the transformed back face for free.", TipCategory.MODERN_MECHANICS, stableId = "rules_tip_modern_mechanics_battles", references = listOf(), query = "battles"))
    add(RuleTip("The Ring tempts you", "Each time the Ring tempts you, choose one of your creatures as Ring-bearer; the Ring's abilities are cumulative (up to four) but only one creature bears it at a time.", TipCategory.MODERN_MECHANICS, stableId = "rules_tip_modern_mechanics_ring_tempts", references = listOf(), query = "Ring tempts"))
    add(RuleTip("Discover", "Discover N exiles cards from the top of your library until a nonland card with mana value N or less appears — cast it for free or put it into your hand. Unlike cascade, the hand is always an option.", TipCategory.MODERN_MECHANICS, stableId = "rules_tip_modern_mechanics_discover", references = listOf(), query = "discover"))
    add(RuleTip("Disguise & cloak", "Both put a card face down as a colorless 2/2 with ward {2}. Disguise lets you turn it face up any time for its disguise cost; cloaked cards flip for their mana cost if they're creatures.", TipCategory.MODERN_MECHANICS, stableId = "rules_tip_modern_mechanics_disguise_cloak", references = listOf(), query = "disguise cloak"))
    add(RuleTip("Plot", "Pay a card's plot cost to exile it from your hand at sorcery speed; on any later turn, cast it from exile for free — also at sorcery speed. Pre-pay this turn, deploy next.", TipCategory.MODERN_MECHANICS, stableId = "rules_tip_modern_mechanics_plot", references = listOf(), query = "plot"))
    add(RuleTip("Committing a crime", "You commit a crime when a spell or ability you put on the stack targets an opponent; a permanent, spell, or ability an opponent controls; or a card in an opponent's graveyard. Targeting a card in exile alone is not a crime. The crime still occurred if the spell or ability is countered.", TipCategory.MODERN_MECHANICS, stableId = "rules_tip_modern_mechanics_committing_crime", references = listOf("700.13"), query = "committing crime"))
    add(RuleTip("Saddle", "Tap any number of your other creatures with total power N or more to saddle a Mount; the Mount gets its saddled bonus for the turn. Saddling happens at sorcery speed.", TipCategory.MODERN_MECHANICS, stableId = "rules_tip_modern_mechanics_saddle", references = listOf(), query = "saddle"))
    add(RuleTip("Rooms", "A Room is a split enchantment: cast it by unlocking one door, and later pay the other door's cost during your main phase to unlock that half too. Each unlocked door's abilities are active.", TipCategory.MODERN_MECHANICS, stableId = "rules_tip_modern_mechanics_room_unlock", references = listOf(), query = "Room unlock"))
    add(RuleTip("Impending", "Cast a spell for its impending cost and it enters with time counters and isn't a creature yet; remove one each of your end steps, and when the last leaves, it wakes up. Cheaper now, scarier later.", TipCategory.MODERN_MECHANICS, stableId = "rules_tip_modern_mechanics_impending", references = listOf(), query = "impending"))
    add(RuleTip("Offspring", "Pay offspring as an additional cost while casting the spell. When the permanent enters, a triggered ability creates a 1/1 copy. The copy has its own enters abilities, but offspring does not double every ability or create the copy before the original enters.", TipCategory.MODERN_MECHANICS, stableId = "rules_tip_modern_mechanics_offspring", references = listOf("702.175a"), query = "offspring"))
    add(RuleTip("Omens", "An Omen is the spell half of a creature card: when the Omen resolves, the card is shuffled into its owner's library instead of going to the graveyard — the creature comes back later.", TipCategory.MODERN_MECHANICS, stableId = "rules_tip_modern_mechanics_omen_cards", references = listOf(), query = "Omen cards"))
    add(RuleTip("Mobilize", "When a creature with mobilize N attacks, you create N tapped and attacking 1/1 red Warrior tokens; sacrifice them at the beginning of the next end step. Free attackers, temporary bodies.", TipCategory.MODERN_MECHANICS, stableId = "rules_tip_modern_mechanics_mobilize", references = listOf(), query = "mobilize"))
    add(RuleTip("Harmonize", "Harmonize lets you cast a card from your graveyard for its harmonize cost and tap up to one untapped creature you control to reduce the generic part of the total cost by that creature's power. A spell cast this way is exiled whenever it would leave the stack.", TipCategory.MODERN_MECHANICS, stableId = "rules_tip_modern_mechanics_harmonize", references = listOf("702.180a"), query = "harmonize"))
    add(RuleTip("Station", "At sorcery timing, station lets you tap another untapped creature you control to put charge counters equal to its power on the station permanent. Printed thresholds unlock abilities; some thresholds also make a Spacecraft a creature.", TipCategory.MODERN_MECHANICS, stableId = "rules_tip_modern_mechanics_station", references = listOf("702.184a", "721.2"), query = "station"))
    add(RuleTip("Warp", "Cast a card from your hand for its warp cost to get it now at a discount; it's exiled at the next end step, and you may cast it again from exile on a later turn for its real cost.", TipCategory.MODERN_MECHANICS, stableId = "rules_tip_modern_mechanics_warp", references = listOf(), query = "warp"))
    add(RuleTip("Void", "Void abilities give a bonus if a nonland permanent left the battlefield this turn or a spell was warped this turn. Sacrifice fodder suddenly pays double.", TipCategory.MODERN_MECHANICS, stableId = "rules_tip_modern_mechanics_void", references = listOf(), query = "void"))
    add(RuleTip("Lander tokens", "A Lander is a colorless artifact token with \"{2}, {T}, Sacrifice this token: search your library for a basic land card, put it onto the battlefield tapped, then shuffle.\" Slow ramp you can bank for later.", TipCategory.MODERN_MECHANICS, stableId = "rules_tip_modern_mechanics_lander_token", references = listOf(), query = "Lander token"))
    add(RuleTip("Start your engines & max speed", "If you control start your engines! and have no speed, your speed becomes 1. Once during each of your own turns, an opponent losing life can trigger a speed increase, up to 4. At speed 4, max speed abilities are active.", TipCategory.MODERN_MECHANICS, stableId = "rules_tip_modern_mechanics_start_your_engines", references = listOf("702.179a", "702.179d", "702.178a"), query = "start your engines"))
    add(RuleTip("Exhaust abilities", "An exhaust ability can be activated only once per game. Spend it at the moment of maximum impact — there is no second chance.", TipCategory.MODERN_MECHANICS, stableId = "rules_tip_modern_mechanics_exhaust", references = listOf(), query = "exhaust"))
}

/** Total tip count — used by [RulesTipWidget]'s daily-selection modulus. */
val MTG_TIPS_COUNT: Int get() = MTG_TIPS_CATALOG.size

/**
 * Fixed seed for the Rules Tip catalog's daily-order shuffle (Home feature overhaul Phase 2.4).
 * A constant seed keeps the permutation stable across restarts and identical for every user.
 */
private const val RULES_TIP_SHUFFLE_SEED = 20260713L

private const val DAY_MS = 86_400_000L

/**
 * The catalog in its fixed daily order: the catalog is grouped by category, so a seeded shuffle
 * avoids long same-category streaks. Indices used by the Home Rules Tip widget point into this list.
 */
val RULES_TIPS_DAILY_ORDER: List<RuleTip> by lazy {
    MTG_TIPS_CATALOG.shuffled(kotlin.random.Random(RULES_TIP_SHUFFLE_SEED))
}

/** Today's tip index into [RULES_TIPS_DAILY_ORDER] (UTC epoch day modulo the catalog size). */
fun dailyRulesTipIndex(nowEpochMs: Long): Int =
    Math.floorMod(nowEpochMs / DAY_MS, RULES_TIPS_DAILY_ORDER.size.toLong()).toInt()

/**
 * A random index into [RULES_TIPS_DAILY_ORDER] that differs from [current] (when more than one tip
 * exists), for the widget's "roll another tip" action.
 */
fun rollRulesTipIndex(current: Int, random: kotlin.random.Random = kotlin.random.Random): Int {
    val size = RULES_TIPS_DAILY_ORDER.size
    if (size <= 1) return 0
    val candidate = random.nextInt(size - 1)
    return if (candidate >= current) candidate + 1 else candidate
}

fun RuleTip.rulesDestination(): com.mmg.manahub.core.model.rules.RulesDestination = when (references.size) {
    0 -> com.mmg.manahub.core.model.rules.RulesDestination.Index(query)
    1 -> com.mmg.manahub.core.model.rules.RulesDestination.Reference("8d860e451f20f38865b725b42d82feb714c725373dd8f3b32b8652b3eeb070ca", references.single())
    else -> com.mmg.manahub.core.model.rules.RulesDestination.References("8d860e451f20f38865b725b42d82feb714c725373dd8f3b32b8652b3eeb070ca", references)
}
