package com.mmg.manahub.core.data.local.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Local cache of a fetched Commander Spellbook `find-my-combos` response (Deck Engine
 * Unification plan D7, Phase 4.3). Mirrors [CommunityAggregateEntity]'s "pure cache, store the
 * raw response verbatim" pattern -- `key` is a hashed canonical card-name-set key (see
 * `com.mmg.manahub.core.data.remote.CommanderSpellbookKeys`, `:shared:core-data`), not an
 * autogenerated id. Holds only transient, re-fetchable data (never user-owned data), so it is
 * safe to overwrite on conflict and evict by age.
 */
@Entity(tableName = "combo_cache")
data class ComboCacheEntity(
    @PrimaryKey
    @ColumnInfo(name = "key") val key: String,
    @ColumnInfo(name = "json") val json: String,
    @ColumnInfo(name = "cached_at") val cachedAt: Long,
)
