package com.mmg.manahub.core.data.local

import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase

/**
 * v47 → v48 — Deck Engine Unification plan (`docs/plans/deck-engine-unification-plan.md`, Phase 4.3)
 * — a new `combo_cache` table caching Commander Spellbook `find-my-combos` responses for the
 * synergy browser's Combos tab.
 *
 * Purely ADDITIVE: a single new table, no FK, no dependents, no existing table touched — mirrors
 * [MIGRATION_43_44]'s `community_aggregate_cache` addition exactly. `key` is a String primary key
 * (a hashed canonical card-name-set, see `com.mmg.manahub.core.data.remote.CommanderSpellbookKeys`),
 * not an autogenerated id.
 *
 * Idempotent: the table is created with `IF NOT EXISTS`, so a retry after a mid-migration crash
 * is safe.
 *
 * Top-level `val` (mirroring [MIGRATION_46_47]) so the instrumented MigrationTestHelper test can
 * reference it directly. Column names/types mirror EXACTLY what Room generates for the new
 * [com.mmg.manahub.core.data.local.entity.ComboCacheEntity] so `runMigrationsAndValidate` passes.
 */
val MIGRATION_47_48 = object : Migration(47, 48) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL(
            """
            CREATE TABLE IF NOT EXISTS `combo_cache` (
                `key` TEXT NOT NULL,
                `json` TEXT NOT NULL,
                `cached_at` INTEGER NOT NULL,
                PRIMARY KEY(`key`)
            )
            """.trimIndent()
        )
    }
}
