package com.mmg.manahub.core.data.local

import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase

/**
 * v43 → v44 — Deck Doctor Community/Archetype plan, Phase 3.3: a new `community_aggregate_cache`
 * table caching Commander (EDHREC-backed) / 60-card (Archidekt-backed) aggregate snapshots served
 * by the `manahub-community` Cloudflare Worker (see `docs/adr/ADR-004-community-api-contracts.md`).
 *
 * Purely ADDITIVE: a single new table, no FK, no dependents, no existing table touched — mirrors
 * [MIGRATION_40_41]'s `community_deck_cache` addition exactly. `key` is a String primary key (the
 * Worker's own cache-key convention), not an autogenerated id.
 *
 * Idempotent: the table is created with `IF NOT EXISTS`, so a retry after a mid-migration crash
 * is safe.
 *
 * Top-level `val` (mirroring [MIGRATION_42_43]) so the instrumented MigrationTestHelper test can
 * reference it directly. Column names/types mirror EXACTLY what Room generates for the new
 * [com.mmg.manahub.core.data.local.entity.CommunityAggregateEntity] so `runMigrationsAndValidate`
 * passes.
 */
val MIGRATION_43_44 = object : Migration(43, 44) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL(
            """
            CREATE TABLE IF NOT EXISTS `community_aggregate_cache` (
                `key` TEXT NOT NULL,
                `json` TEXT NOT NULL,
                `cached_at` INTEGER NOT NULL,
                PRIMARY KEY(`key`)
            )
            """.trimIndent()
        )
    }
}
