package com.mmg.manahub.core.data.local

import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase

/**
 * v48 → v49 — Deck Engine Unification plan (`docs/plans/deck-engine-unification-plan.md`, D8, §5
 * Phase 5c) — a new `card_strategy_tags_cache` table caching the Supabase `card_strategy_tags`
 * table's rows (the offline tag pipeline's precomputed strategy tags, RUN 5), keyed by a card's
 * oracle-wide identity.
 *
 * Purely ADDITIVE: a single new table, no FK, no dependents, no existing table touched — mirrors
 * [MIGRATION_47_48]'s `combo_cache` addition exactly. `oracle_id` is a String primary key, not an
 * autogenerated id.
 *
 * Idempotent: the table is created with `IF NOT EXISTS`, so a retry after a mid-migration crash is
 * safe.
 *
 * Top-level `val` (mirroring [MIGRATION_47_48]) so the instrumented MigrationTestHelper test can
 * reference it directly. Column names/types mirror EXACTLY what Room generates for the new
 * [com.mmg.manahub.core.data.local.entity.CardStrategyTagsCacheEntity] so `runMigrationsAndValidate`
 * passes.
 */
val MIGRATION_48_49 = object : Migration(48, 49) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL(
            """
            CREATE TABLE IF NOT EXISTS `card_strategy_tags_cache` (
                `oracle_id` TEXT NOT NULL,
                `payload_json` TEXT NOT NULL,
                `pipeline_version` TEXT NOT NULL,
                `generated_at` TEXT NOT NULL,
                `fetched_at` INTEGER NOT NULL,
                PRIMARY KEY(`oracle_id`)
            )
            """.trimIndent()
        )
    }
}
