package com.mmg.manahub.feature.draft.data.remote.dto

import com.google.gson.annotations.SerializedName

/**
 * DTO mirroring the Worker's booster.json (§10 schema).
 *
 * `sheets[*].cards` is a JSON **array** of objects with `id` (scryfallId) and `weight` fields,
 * generated by `tools/collation/build-booster.mjs`:
 * ```json
 * { "id": "0200a8c5-…", "weight": 1 }
 * ```
 */
data class BoosterConfigDto(
    @SerializedName("setCode") val setCode: String?,
    @SerializedName("schemaVersion") val schemaVersion: Int?,
    @SerializedName("boosters") val boosters: List<BoosterVariantDto>?,
    @SerializedName("sheets") val sheets: Map<String, BoosterSheetDto>?,
)

data class BoosterVariantDto(
    @SerializedName("weight") val weight: Int?,
    @SerializedName("contents") val contents: Map<String, Int>?,
)

data class BoosterSheetDto(
    @SerializedName("foil") val foil: Boolean?,
    @SerializedName("balanceColors") val balanceColors: Boolean?,
    @SerializedName("cards") val cards: List<BoosterCardEntryDto>?,
)

data class BoosterCardEntryDto(
    @SerializedName("id") val id: String?,
    @SerializedName("weight") val weight: Int?,
)
